// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define EDSLAB_12_FONT_ID (383726265)
#define EDSLAB_14_FONT_ID (637406047)
#define EDSLAB_16_FONT_ID (-989541096)
#define EDSLAB_18_FONT_ID (-29016790)
#define EDSLAB_8_FONT_ID (780054631)
#define NOTOSANS_12_FONT_ID (1597191560)
#define NOTOSANS_14_FONT_ID (-1413326613)
#define NOTOSANS_16_FONT_ID (116566294)
#define NOTOSANS_18_FONT_ID (-348426591)
#define EDSLAB_UI_10_FONT_ID (953619855)
#define EDSLAB_UI_12_FONT_ID (2114776534)
#define EDSLAB_UI_8_FONT_ID (-1004924559)
#define LEGACY_UI_10_FONT_ID (1322569422)
#define LEGACY_UI_12_FONT_ID (1831230762)
#define LEGACY_UI_8_FONT_ID (1465627787)

#if CROSSLINGUA_UI_EDSLAB
#define UI_10_FONT_ID EDSLAB_UI_10_FONT_ID
#define UI_12_FONT_ID EDSLAB_UI_12_FONT_ID
#define SMALL_FONT_ID EDSLAB_UI_8_FONT_ID
#else
#define UI_10_FONT_ID LEGACY_UI_10_FONT_ID
#define UI_12_FONT_ID LEGACY_UI_12_FONT_ID
#define SMALL_FONT_ID LEGACY_UI_8_FONT_ID
#endif

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(EDSLAB_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(EDSLAB_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(EDSLAB_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(EDSLAB_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(EDSLAB_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
